spring.application.name=FirstCopy
spring.datasource.url=jdbc:mysql://localhost:3306/firstcopy
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
logging.level.org.springframework.security=TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
razorpay.key.id=rzp_test_TJNnotZtAmArAZ
razorpay.key.secret=dc0UxheClfy43WM5cpttDgPq
cloudinary.cloud-name=zb3wmd7b
cloudinary.api-key=951545123551292
cloudinary.api-secret=d8sY310wr6g6u4Dc_3Qc1cZfozY
spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB